/* LMAO FFI — C interface for A2A over Waku */

#ifndef LMAO_FFI_H
#define LMAO_FFI_H

/* Auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Discover agents on the Waku network.
 *
 * args_json: { "timeout_ms": 5000 }  (optional, default 5000)
 *
 * Returns: { "success": true, "agents": [ { "name": "...", ... }, ... ] }
 */
char *lmao_discover_agents(const char *args_json);

/**
 * Send a text task to another agent.
 *
 * args_json: { "agent_pubkey": "02...", "task_text": "Hello" }
 *
 * Returns: { "success": true, "task_id": "...", "acked": true/false }
 */
char *lmao_send_task(const char *args_json);

/**
 * Get this agent's card as JSON.
 *
 * Returns: { "success": true, "card": { "name": "...", ... } }
 */
char *lmao_get_agent_card(void);

/**
 * Free a string returned by any lmao_* function.
 */
void lmao_free_string(char *s);

/**
 * Returns the version string of this FFI library.
 */
char *lmao_version(void);

/**
 * Register QtRO delivery callbacks from the C++ module host.
 *
 * Must be called once during module initialization, before any transport
 * operations. The C++ side obtains a delivery_module QtRO replica via
 * `logosAPI->getClient("delivery_module")` and provides function pointers
 * that forward publish/subscribe/unsubscribe calls to the replica.
 *
 * Returns 1 on success, 0 if callbacks were already registered.
 *
 * # Safety
 * All function pointers and `user_data` must remain valid for the process lifetime.
 */
int lmao_qtro_set_callbacks(lmaoPublishFn publish_fn,
                            lmaoSubscribeFn subscribe_fn,
                            lmaoUnsubscribeFn unsubscribe_fn,
                            void *user_data);

#endif  /* LMAO_FFI_H */
